sudo: false
language: node_js
node_js:
  - 14
cache:
  directories:
    - node_modules
os:
  - osx
  - linux
  - windows
before_install:
  - npm update
install:
  - npm install
script:
  - npm test
  - npm run build
after_success: npm run coverage
